CREATE DATABASE IF NOT EXISTS schedule;

USE schedule;

CREATE TABLE IF NOT EXISTS day (
	id INT AUTO_INCREMENT NOT NULL,
	username VARCHAR(255),
	password VARCHAR(255),
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS month(
	id INT AUTO_INCREMENT NOT NULL,
	user INT,
	message VARCHAR(255),
	PRIMARY KEY (id),
	FOREIGN KEY (user) REFERENCES users(id)
);